KLEE: output directory is "/home/zhy/work/test/cap_3_new/bug/aget-0.4.1-llvm/klee-out-0"
KLEE: WARNING: undefined reference to function: __errno_location
KLEE: WARNING: undefined reference to function: __h_errno_location
KLEE: WARNING: undefined reference to function: alarm
KLEE: WARNING: undefined reference to function: atoi
KLEE: WARNING: undefined reference to function: atoll
KLEE: WARNING: undefined reference to function: bzero
KLEE: WARNING: undefined reference to function: close
KLEE: WARNING: undefined reference to function: connect
KLEE: WARNING: undefined reference to function: dup
KLEE: WARNING: undefined reference to function: fclose
KLEE: WARNING: undefined reference to function: fflush
KLEE: WARNING: undefined reference to function: fopen
KLEE: WARNING: undefined reference to function: fprintf
KLEE: WARNING: undefined reference to function: fread
KLEE: WARNING: undefined reference to function: fwrite
KLEE: WARNING: undefined reference to function: gethostbyname
KLEE: WARNING: undefined reference to function: getopt
KLEE: WARNING: undefined reference to function: hstrerror
KLEE: WARNING: undefined reference to function: htons
KLEE: WARNING: undefined reference to function: inet_addr
KLEE: WARNING: undefined reference to function: lseek
KLEE: WARNING: undefined reference to function: open
KLEE: WARNING: undefined reference to variable: optarg
KLEE: WARNING: undefined reference to variable: optind
KLEE: WARNING: undefined reference to function: printf
KLEE: WARNING: undefined reference to function: pthread_cancel
KLEE: WARNING: undefined reference to function: pthread_create
KLEE: WARNING: undefined reference to function: pthread_exit
KLEE: WARNING: undefined reference to function: pthread_join
KLEE: WARNING: undefined reference to function: pthread_mutex_init
KLEE: WARNING: undefined reference to function: pthread_mutex_lock
KLEE: WARNING: undefined reference to function: pthread_mutex_unlock
KLEE: WARNING: undefined reference to function: pthread_self
KLEE: WARNING: undefined reference to function: pthread_sigmask
KLEE: WARNING: undefined reference to function: putchar
KLEE: WARNING: undefined reference to function: pwrite
KLEE: WARNING: undefined reference to function: recv
KLEE: WARNING: undefined reference to function: send
KLEE: WARNING: undefined reference to function: snprintf
KLEE: WARNING: undefined reference to function: socket
KLEE: WARNING: undefined reference to function: sprintf
KLEE: WARNING: undefined reference to variable: stderr
KLEE: WARNING: undefined reference to variable: stdout
KLEE: WARNING: undefined reference to function: strerror
KLEE: WARNING: undefined reference to function: strlen
KLEE: WARNING: undefined reference to function: strncasecmp
KLEE: WARNING: undefined reference to function: strncmp
KLEE: WARNING: undefined reference to function: strncpy
KLEE: WARNING: undefined reference to function: strstr
KLEE: WARNING: undefined reference to function: strtok
KLEE: WARNING: undefined reference to function: time
KLEE: WARNING: undefined reference to function: unlink
KLEE: WARNING: undefined reference to function: vfprintf
KLEE: WARNING: undefined reference to function: write

************************************************************************
第1次执行,路径文件为trace1.txt 初始执行
************************************************************************

KLEE: WARNING ONCE: calling external: pthread_mutex_init(33320736, 0)
KLEE: WARNING ONCE: calling external: getopt(2, 32548672, 33331984)
KLEE: WARNING ONCE: calling external: strlen(33279344)
KLEE: WARNING ONCE: calling external: printf(33349584, 33640352)
KLEE: WARNING ONCE: calling external: strncmp(33640352, 33350192, 6)
KLEE: WARNING ONCE: calling external: strncpy(33592864, 33771888, 5)
KLEE: WARNING ONCE: calling external: gethostbyname(33590816)
KLEE: WARNING ONCE: calling external: time(33339600)
KLEE: WARNING ONCE: calling external: bzero(33892352, 16)
KLEE: WARNING ONCE: calling external: inet_addr(33593888)
KLEE: WARNING ONCE: calling external: htons(80)
KLEE: WARNING ONCE: calling external: socket(2, 1, 0)
KLEE: WARNING ONCE: calling external: connect(8, 33892352, 16)
KLEE: WARNING ONCE: calling external: sprintf(34472336, 33364768, 33360000)
KLEE: WARNING ONCE: calling external: fflush(140036799583232)
http://127.0.0.1/2.txt
size : 5
2
.
t
x
t
req->host : 127.0.0.1
req->ip : 
req->ip : 127.0.0.1
KLEE: WARNING ONCE: calling external: vfprintf(140036799582656, 34472336, 34481664)
<LOG> Head-Request Connection establishedKLEE: WARNING ONCE: calling external: fprintf(140036799582656, 33362304)

KLEE: WARNING ONCE: calling external: send(8, 34423424, 76, 0)
KLEE: WARNING ONCE: calling external: recv(8, 34406592, 512, 0)
KLEE: WARNING ONCE: calling external: strstr(34406592, 33367808)
KLEE: WARNING ONCE: calling external: strtok(34406592, 33378032)
KLEE: WARNING ONCE: calling external: strncasecmp(34406609, 33379296, 15)
KLEE: WARNING ONCE: calling external: atoll(34406785)
<LOG> Downloading /2.txt (4 bytes) from site 127.0.0.1(127.0.0.1:80). Number of Threads: 1
KLEE: WARNING ONCE: calling external: open(33592864, 66, 448)
KLEE: WARNING ONCE: calling external: lseek(9, 3, 0)
KLEE: WARNING ONCE: calling external: write(9, 33344304, 1)
KLEE: WARNING ONCE: calling external: dup(9)
KLEE: WARNING ONCE: calling external: snprintf(34627760, 256, 33346192, 33591840, 33590816, 33346928, 0)
KLEE: WARNING ONCE: calling external: pthread_sigmask(1, 33340848, 0)
KLEE: WARNING ONCE: calling external: pwrite(10, 34803788, 4, 0)
KLEE: WARNING ONCE: calling external: close(11)
req->clength : 4
foffset : 4
td->offset : 4
<LOG> Download completed, job completed in 1 seconds. (0 Kb/sec)
<LOG> Shutting down...
######################本条路径为新路径####################
buildAllFormula  success!

Verifying this trace......

The number of assert: 2
Verifying assert 1 @Trace1#40#E558#1-0assert_bug: Yes!
Assert Failure at /home/zhy/work/test/cap_3_new/bug/aget-0.4.1-llvm/Misc.c: 40

************************************************************************
第2次执行,路径文件为trace2.txt 前缀执行,前缀文件为prefixTrace1#40#E558#1-0assert_bug.txt
************************************************************************

KLEE: ERROR: /home/zhy/work/test/cap_3_new/bug/aget-0.4.1-llvm/Misc.c:40: ASSERTION FAIL: assert1 == temp
KLEE: NOTE: now ignoring this error at this location
encounter runtime error
######################执行有错误,放弃本次执行##############

KLEE: done: total instructions = 6343
KLEE: done: completed paths = 2
KLEE: done: generated tests = 0
http://127.0.0.1/2.txt
