KLEE: output directory is "/home/zhy/git/Benchmarks/cap_3_new/bug/aget-0.4.1-llvm/klee-out-0"
KLEE: WARNING: undefined reference to function: __errno_location
KLEE: WARNING: undefined reference to function: __h_errno_location
KLEE: WARNING: undefined reference to function: alarm
KLEE: WARNING: undefined reference to function: atoi
KLEE: WARNING: undefined reference to function: atoll
KLEE: WARNING: undefined reference to function: bzero
KLEE: WARNING: undefined reference to function: close
KLEE: WARNING: undefined reference to function: connect
KLEE: WARNING: undefined reference to function: dup
KLEE: WARNING: undefined reference to function: fclose
KLEE: WARNING: undefined reference to function: fflush
KLEE: WARNING: undefined reference to function: fopen
KLEE: WARNING: undefined reference to function: fprintf
KLEE: WARNING: undefined reference to function: fread
KLEE: WARNING: undefined reference to function: fwrite
KLEE: WARNING: undefined reference to function: gethostbyname
KLEE: WARNING: undefined reference to function: getopt
KLEE: WARNING: undefined reference to function: hstrerror
KLEE: WARNING: undefined reference to function: htons
KLEE: WARNING: undefined reference to function: inet_addr
KLEE: WARNING: undefined reference to function: lseek
KLEE: WARNING: undefined reference to function: open
KLEE: WARNING: undefined reference to variable: optarg
KLEE: WARNING: undefined reference to variable: optind
KLEE: WARNING: undefined reference to function: printf
KLEE: WARNING: undefined reference to function: pthread_cancel
KLEE: WARNING: undefined reference to function: pthread_create
KLEE: WARNING: undefined reference to function: pthread_exit
KLEE: WARNING: undefined reference to function: pthread_join
KLEE: WARNING: undefined reference to function: pthread_mutex_init
KLEE: WARNING: undefined reference to function: pthread_mutex_lock
KLEE: WARNING: undefined reference to function: pthread_mutex_unlock
KLEE: WARNING: undefined reference to function: pthread_self
KLEE: WARNING: undefined reference to function: pthread_sigmask
KLEE: WARNING: undefined reference to function: putchar
KLEE: WARNING: undefined reference to function: pwrite
KLEE: WARNING: undefined reference to function: recv
KLEE: WARNING: undefined reference to function: send
KLEE: WARNING: undefined reference to function: snprintf
KLEE: WARNING: undefined reference to function: socket
KLEE: WARNING: undefined reference to function: sprintf
KLEE: WARNING: undefined reference to variable: stderr
KLEE: WARNING: undefined reference to variable: stdout
KLEE: WARNING: undefined reference to function: strerror
KLEE: WARNING: undefined reference to function: strlen
KLEE: WARNING: undefined reference to function: strncasecmp
KLEE: WARNING: undefined reference to function: strncmp
KLEE: WARNING: undefined reference to function: strncpy
KLEE: WARNING: undefined reference to function: strstr
KLEE: WARNING: undefined reference to function: strtok
KLEE: WARNING: undefined reference to function: time
KLEE: WARNING: undefined reference to function: unlink
KLEE: WARNING: undefined reference to function: vfprintf
KLEE: WARNING: undefined reference to function: write

************************************************************************
第1次执行,路径文件为trace1.txt 初始执行
************************************************************************

KLEE: WARNING ONCE: calling external: pthread_mutex_init(48259008, 0)
KLEE: WARNING ONCE: calling external: getopt(2, 47709952, 48270208)
KLEE: WARNING ONCE: calling external: strlen(47479664)
KLEE: WARNING ONCE: calling external: printf(48287856, 48578560)
KLEE: WARNING ONCE: calling external: strncmp(48578560, 48288464, 6)
KLEE: WARNING ONCE: calling external: strncpy(48531072, 48710096, 5)
KLEE: WARNING ONCE: calling external: gethostbyname(48529024)
KLEE: WARNING ONCE: calling external: time(48277824)
KLEE: WARNING ONCE: calling external: bzero(48946736, 16)
KLEE: WARNING ONCE: calling external: inet_addr(48532096)
KLEE: WARNING ONCE: calling external: htons(80)
KLEE: WARNING ONCE: calling external: socket(2, 1, 0)
KLEE: WARNING ONCE: calling external: connect(8, 48946736, 16)
KLEE: WARNING ONCE: calling external: sprintf(49413952, 48302992, 48312240)
KLEE: WARNING ONCE: calling external: fflush(140263073694720)
http://127.0.0.1/2.txt
size : 5
2
.
t
x
t
req->host : 127.0.0.1
req->ip : 
req->ip : 127.0.0.1
KLEE: WARNING ONCE: calling external: vfprintf(140263073694144, 49413952, 49419968)
<LOG> Head-Request Connection establishedKLEE: WARNING ONCE: calling external: fprintf(140263073694144, 48300528)

KLEE: WARNING ONCE: calling external: send(8, 49362016, 76, 0)
KLEE: WARNING ONCE: calling external: recv(8, 49345248, 512, 0)
KLEE: WARNING ONCE: calling external: strstr(49345248, 48306032)
KLEE: WARNING ONCE: calling external: strtok(49345248, 48316256)
KLEE: WARNING ONCE: calling external: strncasecmp(49345265, 48317520, 15)
KLEE: WARNING ONCE: calling external: atoll(49345441)
<LOG> Downloading /2.txt (4 bytes) from site 127.0.0.1(127.0.0.1:80). Number of Threads: 1
KLEE: WARNING ONCE: calling external: open(48531072, 66, 448)
KLEE: WARNING ONCE: calling external: lseek(9, 3, 0)
KLEE: WARNING ONCE: calling external: write(9, 48282576, 1)
KLEE: WARNING ONCE: calling external: dup(9)
KLEE: WARNING ONCE: calling external: snprintf(49561056, 256, 48284464, 48530048, 48529024, 48285200, 0)
KLEE: WARNING ONCE: calling external: pthread_sigmask(1, 48279072, 0)
KLEE: WARNING ONCE: calling external: pwrite(10, 49741836, 4, 0)
KLEE: WARNING ONCE: calling external: close(11)
req->clength : 4
foffset : 4
td->offset : 4
<LOG> Download completed, job completed in 1 seconds. (0 Kb/sec)
<LOG> Shutting down...
######################本条路径为新路径####################
buildAllFormula  success!

Verifying this trace......

The number of assert: 2
Verifying assert 1 @Trace1#40#E558#1-0assert_bug: Yes!
Assert Failure at /home/zhy/git/Benchmarks/cap_3_new/bug/aget-0.4.1-llvm/Misc.c: 40

************************************************************************
第2次执行,路径文件为trace2.txt 前缀执行,前缀文件为prefixTrace1#40#E558#1-0assert_bug.txt
************************************************************************

KLEE: ERROR: /home/zhy/git/Benchmarks/cap_3_new/bug/aget-0.4.1-llvm/Misc.c:40: ASSERTION FAIL: assert1 == temp
KLEE: NOTE: now ignoring this error at this location
encounter runtime error
######################执行有错误,放弃本次执行##############

KLEE: done: total instructions = 6343
KLEE: done: completed paths = 2
KLEE: done: generated tests = 0
http://127.0.0.1/2.txt
